/**
 * Render the wave-2 exports: vessel ETA and trucking daily planning.
 *
 * Why these two, and why they are safe to carry: SAP never sends either. Measured, not assumed -
 * across 27,003 sap_processed_data rows the ETA keys appear 0 times (against 1,800 for ATA), and
 * `daily_deliverables` has no SAP writer at all. So every value here was typed by a user, and
 * production will never produce it on its own. Left behind, it is simply lost.
 *
 * Both are keyed by business identity, never UUID. ETA additionally carries the port's identity
 * within its shipment - sequence and loading-vs-discharge - because that is how the application
 * itself matches a port row (vesselLoadingPortsFromSap).
 *
 *   npx ts-node src/scripts/renderEtaPlanningExportSql.ts
 */
import * as fs from 'fs';
import * as path from 'path';

const OUT_DIR = path.join(process.cwd(), '..', 'docs', 'scripts', 'sql');

/**
 * Two grains in one file, told apart by `scope`.
 *
 * ETA lives at both levels and both are read: `sqlContractHasNoRegisteredEtaExpr` checks the
 * shipment's own eta_* columns AND the port rows'. Exporting only one would leave the page still
 * treating the contract as having no registered ETA.
 */
const ETA_SQL = `-- GENERATED by backend/src/scripts/renderEtaPlanningExportSql.ts - do not edit by hand.
--
-- Wave 2a export: vessel ETA, at both the port and the shipment grain.
--
-- Emits CSV on stdout. Read-only.
--
-- SAP never supplies ETA (0 occurrences across 27,003 SAP rows), so every value here is user
-- input that production cannot recreate.
COPY (
  -- Port-level ETA. port_sequence + is_discharge_port is how the application matches a port row.
  SELECT
    'port'                                        AS scope,
    TRIM(c.po_number::text)                       AS po_number,
    TRIM(c.contract_id::text)                     AS contract_number,
    COALESCE(NULLIF(TRIM(s.shipment_id), ''), '') AS shipment_key,
    vlp.port_sequence                             AS port_sequence,
    COALESCE(vlp.is_discharge_port, FALSE)        AS is_discharge_port,
    COALESCE(NULLIF(TRIM(vlp.port_name), ''), '') AS port_name,
    vlp.eta_vessel_arrival,
    vlp.eta_vessel_berthed,
    vlp.eta_loading_start,
    vlp.eta_loading_completed,
    vlp.eta_vessel_sailed,
    vlp.eta_vessel_berthed_at_loading_port,
    vlp.eta_vessel_arrive_at_discharge_port,
    vlp.eta_vessel_berthed_at_discharge_port,
    vlp.eta_vessel_start_discharging,
    vlp.eta_vessel_complete_discharge,
    NULL::numeric AS sfal_qty,
    NULL::numeric AS sfbd_qty
  FROM vessel_loading_ports vlp
  INNER JOIN shipments s ON s.id = vlp.shipment_id
  INNER JOIN contracts c ON c.id = s.contract_id
  WHERE NULLIF(TRIM(c.po_number::text), '') IS NOT NULL
    AND UPPER(COALESCE(s.status, '')) NOT IN ('CANCELLED', 'CANCELED')
    AND COALESCE(
      vlp.eta_vessel_arrival, vlp.eta_vessel_berthed, vlp.eta_loading_start,
      vlp.eta_loading_completed, vlp.eta_vessel_sailed,
      vlp.eta_vessel_berthed_at_loading_port, vlp.eta_vessel_arrive_at_discharge_port,
      vlp.eta_vessel_berthed_at_discharge_port, vlp.eta_vessel_start_discharging,
      vlp.eta_vessel_complete_discharge
    ) IS NOT NULL

  UNION ALL

  -- Shipment-level ETA. NULL port_sequence marks the grain; the loader writes shipments.eta_*.
  SELECT
    'shipment'                                    AS scope,
    TRIM(c.po_number::text)                       AS po_number,
    TRIM(c.contract_id::text)                     AS contract_number,
    COALESCE(NULLIF(TRIM(s.shipment_id), ''), '') AS shipment_key,
    NULL::int                                     AS port_sequence,
    FALSE                                         AS is_discharge_port,
    ''                                            AS port_name,
    s.eta_arrival,
    s.eta_berthed,
    s.eta_loading_start,
    s.eta_loading_complete,
    s.eta_sailed,
    NULL::timestamp,
    s.eta_discharge_arrival,
    s.eta_discharge_berthed,
    s.eta_discharge_start,
    s.eta_discharge_complete,
    s.sfal_qty,
    s.sfbd_qty
  FROM shipments s
  INNER JOIN contracts c ON c.id = s.contract_id
  WHERE NULLIF(TRIM(c.po_number::text), '') IS NOT NULL
    AND UPPER(COALESCE(s.status, '')) NOT IN ('CANCELLED', 'CANCELED')
    AND (
      COALESCE(
        s.eta_arrival, s.eta_berthed, s.eta_loading_start, s.eta_loading_complete, s.eta_sailed,
        s.eta_discharge_arrival, s.eta_discharge_berthed, s.eta_discharge_start,
        s.eta_discharge_complete
      ) IS NOT NULL
      -- SFAL/SFBD are carried on the same row and are KLIP-only in their own right, so a shipment
      -- holding only those still has something worth migrating.
      OR s.sfal_qty IS NOT NULL OR s.sfbd_qty IS NOT NULL
    )

  ORDER BY 2, 1, 5 NULLS FIRST, 6
) TO STDOUT WITH CSV HEADER;
`;

/**
 * Trucking planning. `daily_deliverables` is jsonb and travels whole - it is one editable unit in
 * the UI, and splitting it per day would let a partial load leave a half-plan behind.
 */
const PLANNING_SQL = `-- GENERATED by backend/src/scripts/renderEtaPlanningExportSql.ts - do not edit by hand.
--
-- Wave 2b export: trucking daily planning.
--
-- Emits CSV on stdout. Read-only.
--
-- SAP has no writer for daily_deliverables, so a plan is proof of KLIP authorship on its own -
-- no provenance argument is needed, unlike the ATA and quantity columns.
COPY (
  SELECT
    TRIM(c.po_number::text)                       AS po_number,
    TRIM(c.contract_id::text)                     AS contract_number,
    t.daily_deliverables::text                    AS daily_deliverables,
    t.last_daily_deliverable_date,
    t.trucking_start_date,
    t.trucking_completion_date,
    t.sfal_qty,
    t.sfbd_qty
  FROM trucking_operations t
  INNER JOIN contracts c ON c.id = t.contract_id
  WHERE t.deduped_at IS NULL
    AND UPPER(COALESCE(t.status, '')) NOT IN ('CANCELLED', 'CANCELED')
    AND NULLIF(TRIM(c.po_number::text), '') IS NOT NULL
    AND (
      jsonb_array_length(COALESCE(NULLIF(t.daily_deliverables, 'null'::jsonb), '[]'::jsonb)) > 0
      -- SFAL/SFBD on trucking are KLIP-only (migration 148 has no SAP writer), so an operation
      -- carrying only those is still worth migrating.
      OR t.sfal_qty IS NOT NULL OR t.sfbd_qty IS NOT NULL
    )
  ORDER BY 1
) TO STDOUT WITH CSV HEADER;
`;

fs.mkdirSync(OUT_DIR, { recursive: true });
for (const [name, sql] of [
  ['migrate-eta-export.sql', ETA_SQL],
  ['migrate-planning-export.sql', PLANNING_SQL],
] as const) {
  const out = path.join(OUT_DIR, name);
  fs.writeFileSync(out, sql, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`wrote ${out} (${(sql.length / 1024).toFixed(1)} KB)`);
}
