/**
 * Render the staging inventory that has to be read BEFORE deciding on a staging->production
 * migration of operational data.
 *
 * It classifies every operational row into one of three buckets - carry, drop, decide - using the
 * markers the application itself already maintains, and counts them. The point is to replace
 * "staging is probably dirty" with a number for each kind of dirt.
 *
 * Read-only. The scope predicates are rendered from the app's own builders so a row counted as
 * carryable here is a row the pages would actually accept.
 *
 *   npx ts-node src/scripts/renderOperationalMigrationInventorySql.ts
 *   psql "$CONN" -f docs/scripts/sql/inventory-operational-migration.sql
 */
import * as fs from 'fs';
import * as path from 'path';
import { contractEffectiveIncotermExpr } from '../utils/truckingIncotermScope';
import { buildShipmentPageSeaIncotermScopeSql } from '../utils/shipmentIncotermScope';

const OUT = path.join(
  process.cwd(),
  '..',
  'docs',
  'scripts',
  'sql',
  'inventory-operational-migration.sql',
);

const inc = contractEffectiveIncotermExpr('c');
const seaScope = buildShipmentPageSeaIncotermScopeSql('c');
const landScope = `${inc} IN ('FRC', 'LCO')`;

const sql = `-- GENERATED by backend/src/scripts/renderOperationalMigrationInventorySql.ts - do not edit.
--
-- Inventory of operational data in STAGING, classified for a migration to production.
--
--   psql "$CONN" -f inventory-operational-migration.sql
--
-- Read-only: SELECT only, no writes, no temp tables.
--
-- Three buckets:
--   CARRY   the row is the kind production cannot recreate from SAP, and it passes the
--           application's own validity markers
--   DROP    the application already considers it superseded or void (soft-deduped, cancelled,
--           SAP-sourced and therefore recreated on import)
--   DECIDE  it is neither clearly valid nor clearly void - a human has to look
\\set ON_ERROR_STOP on
\\pset footer off

\\echo ''
\\echo '######## 1. TRUCKING OPERATIONS ########'
\\echo '-- deduped_at is the soft-dedupe marker (migration 137); cancelled rows are excluded from'
\\echo '-- matching everywhere in the app (truckingOperationUniqueness.ts).'
SELECT
  CASE
    WHEN t.deduped_at IS NOT NULL                                   THEN 'DROP  soft-deduped loser'
    WHEN UPPER(COALESCE(t.status, '')) IN ('CANCELLED','CANCELED')   THEN 'DROP  cancelled'
    WHEN t.contract_id IS NULL                                       THEN 'DROP  no contract'
    WHEN NULLIF(TRIM(c.po_number::text), '') IS NULL                 THEN 'DECIDE  contract has no PO number'
    WHEN NOT (${landScope})                                          THEN 'DECIDE  contract not FRC/LCO'
    WHEN UPPER(COALESCE(NULLIF(TRIM(c.transport_mode), ''), '')) = 'SEA' THEN 'DROP  sea contract (migration 077)'
    ELSE 'CARRY'
  END AS bucket,
  COUNT(*)::int AS operations
FROM trucking_operations t
LEFT JOIN contracts c ON c.id = t.contract_id
GROUP BY 1 ORDER BY 1;

\\echo ''
\\echo '-- Of the CARRY operations, how many actually hold work a user did?'
\\echo '-- An operation with no WB rows, no realization and no planning is nothing to migrate:'
\\echo '-- the SAP import recreates an empty operation on its own.'
SELECT
  CASE
    WHEN da.n > 0                                   THEN 'has WB daily actuals'
    WHEN r.trucking_operation_id IS NOT NULL
     AND LOWER(COALESCE(r.source, '')) NOT IN ('sap','sap_migrated')
                                                    THEN 'has manual realization only'
    WHEN jsonb_array_length(COALESCE(NULLIF(t.daily_deliverables, 'null'::jsonb), '[]'::jsonb)) > 0
                                                    THEN 'has planning only'
    WHEN NULLIF(TRIM(COALESCE(t.loading_location, '')), '') IS NOT NULL
      OR NULLIF(TRIM(COALESCE(t.unloading_location, '')), '') IS NOT NULL
                                                    THEN 'has locations only'
    ELSE 'EMPTY - only SAP-derived data, production recreates it'
  END AS content,
  COUNT(*)::int AS operations
FROM trucking_operations t
JOIN contracts c ON c.id = t.contract_id
LEFT JOIN trucking_realizations r ON r.trucking_operation_id = t.id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS n FROM trucking_daily_actuals d WHERE d.trucking_operation_id = t.id
) da ON TRUE
WHERE t.deduped_at IS NULL
  AND UPPER(COALESCE(t.status, '')) NOT IN ('CANCELLED','CANCELED')
  AND NULLIF(TRIM(c.po_number::text), '') IS NOT NULL
  AND (${landScope})
GROUP BY 1 ORDER BY 2 DESC;

\\echo ''
\\echo '######## 2. WB DAILY ACTUALS ########'
\\echo '-- The blank-STO shadow rows of migration 124 double-counted quantities. Any left here'
\\echo '-- must not be carried.'
SELECT
  CASE
    WHEN t.id IS NULL                       THEN 'DROP  orphan (no operation)'
    WHEN t.deduped_at IS NOT NULL           THEN 'DROP  operation is a deduped loser'
    WHEN UPPER(COALESCE(t.status,'')) IN ('CANCELLED','CANCELED') THEN 'DROP  operation cancelled'
    WHEN shadow.n > 0                       THEN 'DROP  blank-STO row shadowed by STO rows (migration 124)'
    WHEN d.quantity_kg IS NULL AND d.quantity_delivery_kg IS NULL AND d.quantity_receive_kg IS NULL
                                            THEN 'DECIDE  no quantity at all'
    WHEN COALESCE(d.quantity_kg, 0) < 0 OR COALESCE(d.quantity_delivery_kg, 0) < 0
      OR COALESCE(d.quantity_receive_kg, 0) < 0
                                            THEN 'DECIDE  negative quantity'
    ELSE 'CARRY'
  END AS bucket,
  COUNT(*)::int AS rows
FROM trucking_daily_actuals d
LEFT JOIN trucking_operations t ON t.id = d.trucking_operation_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS n
  FROM trucking_daily_actuals d2
  WHERE d2.trucking_operation_id = d.trucking_operation_id
    AND d2.progress_date = d.progress_date
    AND NULLIF(TRIM(COALESCE(d2.sto_number, '')), '') IS NOT NULL
) shadow ON NULLIF(TRIM(COALESCE(d.sto_number, '')), '') IS NULL
GROUP BY 1 ORDER BY 2 DESC;

\\echo ''
\\echo '######## 3. TRUCKING REALIZATIONS ########'
\\echo '-- source=sap/sap_migrated is recreated by the production import; only manual rows are'
\\echo '-- user work. end < start is checked nowhere in the app - it has to be checked here.'
SELECT
  CASE
    WHEN t.id IS NULL                            THEN 'DROP  orphan (no operation)'
    WHEN LOWER(COALESCE(r.source, '')) IN ('sap','sap_migrated') THEN 'DROP  SAP-sourced, import recreates it'
    WHEN r.realization_start_date IS NOT NULL AND r.realization_end_date IS NOT NULL
     AND r.realization_end_date < r.realization_start_date       THEN 'DECIDE  end before start'
    WHEN r.realization_start_date IS NULL AND r.realization_end_date IS NULL THEN 'DECIDE  both dates empty'
    ELSE 'CARRY'
  END AS bucket,
  COUNT(*)::int AS rows
FROM trucking_realizations r
LEFT JOIN trucking_operations t ON t.id = r.trucking_operation_id
GROUP BY 1 ORDER BY 2 DESC;

\\echo ''
\\echo '######## 4. SHIPMENTS ########'
\\echo '-- This is the table that would make GR-closed sea POs visible again on the Shipment page.'
SELECT
  CASE
    WHEN s.contract_id IS NULL                                     THEN 'DROP  no contract'
    WHEN UPPER(COALESCE(s.status,'')) IN ('CANCELLED','CANCELED')  THEN 'DECIDE  cancelled'
    WHEN NULLIF(TRIM(c.po_number::text), '') IS NULL               THEN 'DECIDE  contract has no PO number'
    WHEN NOT (${seaScope})                                         THEN 'DECIDE  contract not CIF/FOB/CFR'
    WHEN NULLIF(TRIM(COALESCE(s.shipment_id, '')), '') IS NULL     THEN 'DECIDE  no shipment_id (STO) key'
    ELSE 'CARRY'
  END AS bucket,
  COUNT(*)::int AS shipments
FROM shipments s
LEFT JOIN contracts c ON c.id = s.contract_id
GROUP BY 1 ORDER BY 2 DESC;

\\echo ''
\\echo '-- Which shipments hold user work SAP could not recreate?'
SELECT
  CASE
    WHEN vlp.n > 0                                               THEN 'has loading/discharge ports (ETA/ATA)'
    WHEN NULLIF(TRIM(COALESCE(s.vessel_name, '')), '') IS NOT NULL THEN 'has vessel name only'
    WHEN COALESCE(s.quantity_delivered_klip, 0) > 0              THEN 'has KLIP delivered qty only'
    ELSE 'EMPTY - nothing a user added'
  END AS content,
  COUNT(*)::int AS shipments
FROM shipments s
JOIN contracts c ON c.id = s.contract_id
LEFT JOIN LATERAL (
  SELECT COUNT(*)::int AS n FROM vessel_loading_ports v WHERE v.shipment_id = s.id
) vlp ON TRUE
WHERE UPPER(COALESCE(s.status,'')) NOT IN ('CANCELLED','CANCELED')
  AND NULLIF(TRIM(c.po_number::text), '') IS NOT NULL
GROUP BY 1 ORDER BY 2 DESC;

\\echo ''
\\echo '######## 5. VESSEL LOADING PORTS ########'
\\echo '-- No UNIQUE constraint exists on this table, so duplicates are possible in staging AND'
\\echo '-- a re-run of the migration would create more. Count the de-facto key collisions now.'
SELECT
  CASE WHEN dup.n > 1 THEN 'DECIDE  duplicate (shipment, port_sequence, is_discharge_port)' ELSE 'CARRY' END AS bucket,
  COUNT(*)::int AS rows
FROM vessel_loading_ports v
JOIN LATERAL (
  SELECT COUNT(*)::int AS n
  FROM vessel_loading_ports v2
  WHERE v2.shipment_id = v.shipment_id
    AND COALESCE(v2.port_sequence, -1) = COALESCE(v.port_sequence, -1)
    AND COALESCE(v2.is_discharge_port, FALSE) = COALESCE(v.is_discharge_port, FALSE)
) dup ON TRUE
GROUP BY 1 ORDER BY 2 DESC;

\\echo ''
\\echo '######## 6. TEXT-KEYED TABLES (no UUID remapping needed) ########'
SELECT 'user_sto_contract_assignments' AS table_name, COUNT(*)::int AS rows FROM user_sto_contract_assignments
UNION ALL SELECT 'commercial_document_files', COUNT(*)::int FROM commercial_document_files
UNION ALL SELECT 'settlement_invoice_summaries', COUNT(*)::int FROM settlement_invoice_summaries
UNION ALL SELECT 'claim_susut_rows', COUNT(*)::int FROM claim_susut_rows
UNION ALL SELECT 'claim_mutu_rows', COUNT(*)::int FROM claim_mutu_rows
UNION ALL SELECT 'remarks', COUNT(*)::int FROM remarks
UNION ALL SELECT 'documents', COUNT(*)::int FROM documents
UNION ALL SELECT 'trucking_wb_imports', COUNT(*)::int FROM trucking_wb_imports
ORDER BY 1;

\\echo ''
\\echo '######## 7. THE DECIDING NUMBER ########'
\\echo '-- How much user work exists that production cannot recreate by itself?'
SELECT
  (SELECT COUNT(*)::int FROM trucking_daily_actuals) AS wb_rows_total,
  (SELECT COUNT(DISTINCT d.trucking_operation_id)::int
     FROM trucking_daily_actuals d
     JOIN trucking_operations t ON t.id = d.trucking_operation_id
    WHERE t.deduped_at IS NULL
      AND UPPER(COALESCE(t.status,'')) NOT IN ('CANCELLED','CANCELED')) AS ops_with_wb_carryable,
  (SELECT COUNT(*)::int FROM vessel_loading_ports)   AS vlp_rows_total,
  (SELECT COUNT(*)::int FROM shipments s
    WHERE UPPER(COALESCE(s.status,'')) NOT IN ('CANCELLED','CANCELED')) AS shipments_not_cancelled;
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, sql, 'utf8');
// eslint-disable-next-line no-console
console.log(`wrote ${OUT} (${(sql.length / 1024).toFixed(1)} KB)`);
