/**
 * Render the WB daily-actuals export used by wave 1 of the staging -> production migration.
 *
 * Why WB first: `trucking_daily_actuals` is the one operational table the SAP import never writes,
 * so every row in it came from a user - by manual entry or by WB upload. It needs no provenance
 * argument, which is exactly what the ATA columns cannot offer. It is also the data users cannot
 * reasonably retype: weighbridge quantities, day by day.
 *
 * The export is keyed by BUSINESS keys (PO number, STO number, date), never by UUID: `contracts.id`
 * and `trucking_operations.id` differ between environments, and migration 119 made TRIM(po_number)
 * the stable identity.
 *
 *   npx ts-node src/scripts/renderWbMigrationExportSql.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { contractEffectiveIncotermExpr } from '../utils/truckingIncotermScope';

const OUT = path.join(process.cwd(), '..', 'docs', 'scripts', 'sql', 'migrate-wb-export.sql');

const inc = contractEffectiveIncotermExpr('c');

const sql = `-- GENERATED by backend/src/scripts/renderWbMigrationExportSql.ts - do not edit by hand.
--
-- Wave 1 export: WB daily actuals that are safe to carry to production.
--
-- Emits CSV on stdout. Read-only.
--
-- Carried only when every one of these holds, and each is a rule the application itself already
-- applies - none of it is invented here:
--   * the operation is not a soft-deduped loser        (migration 137, deduped_at)
--   * the operation is not cancelled                   (excluded from matching everywhere)
--   * its contract has a PO number                     (migration 119 identity; without it the
--                                                       row cannot be re-anchored in production)
--   * the contract is FRC/LCO and not SEA              (trucking page scope, migration 077)
--   * the row is not a blank-STO row shadowed by
--     per-STO rows for the same operation and date     (migration 124 - these double-counted)
--   * it carries at least one non-negative quantity
COPY (
  SELECT
    TRIM(c.po_number::text)                                  AS po_number,
    TRIM(c.contract_id::text)                                AS contract_number,
    COALESCE(NULLIF(TRIM(d.sto_number), ''), '')             AS sto_number,
    d.progress_date::date                                    AS progress_date,
    d.quantity_kg,
    d.quantity_delivery_kg,
    d.quantity_receive_kg,
    COALESCE(d.source, '')                                   AS source
  FROM trucking_daily_actuals d
  INNER JOIN trucking_operations t ON t.id = d.trucking_operation_id
  INNER JOIN contracts c           ON c.id = t.contract_id
  WHERE t.deduped_at IS NULL
    AND UPPER(COALESCE(t.status, '')) NOT IN ('CANCELLED', 'CANCELED')
    AND NULLIF(TRIM(c.po_number::text), '') IS NOT NULL
    AND ${inc} IN ('FRC', 'LCO')
    AND UPPER(COALESCE(NULLIF(TRIM(c.transport_mode), ''), '')) <> 'SEA'
    AND NOT (
      NULLIF(TRIM(COALESCE(d.sto_number, '')), '') IS NULL
      AND EXISTS (
        SELECT 1 FROM trucking_daily_actuals d2
        WHERE d2.trucking_operation_id = d.trucking_operation_id
          AND d2.progress_date = d.progress_date
          AND NULLIF(TRIM(COALESCE(d2.sto_number, '')), '') IS NOT NULL
      )
    )
    AND COALESCE(d.quantity_kg, 0) >= 0
    AND COALESCE(d.quantity_delivery_kg, 0) >= 0
    AND COALESCE(d.quantity_receive_kg, 0) >= 0
    AND (d.quantity_kg IS NOT NULL OR d.quantity_delivery_kg IS NOT NULL OR d.quantity_receive_kg IS NOT NULL)
  ORDER BY 1, 3, 4
) TO STDOUT WITH CSV HEADER;
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, sql, 'utf8');
// eslint-disable-next-line no-console
console.log(`wrote ${OUT} (${(sql.length / 1024).toFixed(1)} KB)`);
