/**
 * Render a self-contained SQL diagnostic answering "why is this PO not on the Shipment page?".
 *
 * The expressions are taken from the page's own builders rather than retyped, because a
 * hand-copied predicate that drifts from the real one produces a confident wrong answer - which
 * is worse than no diagnostic at all. Rendering also means the file can be run with plain psql on
 * a server that has no ts-node.
 *
 *   npx ts-node src/scripts/renderShipmentPoVisibilitySql.ts
 *   psql ... -v po=1001031325 -f docs/scripts/sql/diag-shipment-po-visibility.sql
 */
import * as fs from 'fs';
import * as path from 'path';
import { contractEffectiveIncotermExpr } from '../utils/truckingIncotermScope';
import {
  buildShipmentSeaMixTransportSql,
  shipmentResolvedStoTypeForNumberExpr,
} from '../utils/shipmentStoTypeSql';
import { buildShipmentPageSeaIncotermScopeSql } from '../utils/shipmentIncotermScope';
import {
  sqlIsContractSapInactiveForShipmentBacklogExpr,
  SQL_CONTRACT_IMPORT_STATUS,
} from '../utils/contractDeliveryStatus';
import { sqlContractSharesNumericStoWithActiveSeaShipmentExpr } from '../utils/seaStoSiblingSql';

const OUT = path.join(process.cwd(), '..', 'docs', 'scripts', 'sql', 'diag-shipment-po-visibility.sql');

/*
 * The page evaluates its scope against `c` (contracts), `l` (latest SPD) and `s` (shipments).
 * Only `c` exists here - this report is about the PO as a whole rather than one list row - so the
 * STO type is resolved by number, which uses the contract_stos and SAP arms and needs no join.
 *
 * The sea-row scope is then composed from those two rendered pieces rather than retyped: incoterm
 * in CIF/FOB/CFR, and not the FOB-Type-T trucking leg. That composition is the one line here that
 * mirrors buildShipmentPageSeaRowScopeSql instead of being rendered from it.
 */
const incoterm = contractEffectiveIncotermExpr('c');
const incotermInScope = buildShipmentPageSeaIncotermScopeSql('c');
const stoType = shipmentResolvedStoTypeForNumberExpr('c', 'c.sto_number::text');
const seaRowScope = `(${incotermInScope}) AND NOT ((${incoterm}) = 'FOB' AND ${stoType} = 'T')`;
const transport = buildShipmentSeaMixTransportSql('c');
const backlogInactive = sqlIsContractSapInactiveForShipmentBacklogExpr('c');
const sharesSto = sqlContractSharesNumericStoWithActiveSeaShipmentExpr('c.id');

const sql = `-- GENERATED by backend/src/scripts/renderShipmentPoVisibilitySql.ts - do not edit by hand.
--
-- Why is a PO on the Shipment page in one environment and not the other?
--
-- Run the SAME file on both, then compare the two outputs line by line. Every predicate below is
-- the page's own, rendered from its builders, so a "false" here is the actual reason the row is
-- absent rather than an approximation of it.
--
--   psql "$CONN" -v po=1001031325 -f diag-shipment-po-visibility.sql
--
-- A row reaches the Shipment page by one of two paths, and needs only one of them:
--   execution : a shipments row exists, and the PO passes the sea scope and sap_presence
--   backlog   : no shipments row, and the PO passes the sea scope, is not GR-Close/Cancelled,
--               is not a B2B child, has no registered ETA, and no sibling contract on the same
--               numeric STO already has an active shipment
\\set ON_ERROR_STOP on
\\echo '=== 1. contract ==='
SELECT
  c.contract_id,
  c.po_number,
  c.sto_number,
  c.incoterm                                   AS incoterm_raw,
  ${incoterm}                                  AS incoterm_effective,
  ${incotermInScope}                           AS incoterm_in_scope,
  ${stoType}                                   AS sto_type_resolved,
  ${seaRowScope}                               AS passes_sea_row_scope,
  ${transport}                                 AS transport_sea_or_mix,
  COALESCE(c.sap_presence, 'PRESENT')          AS sap_presence,
  c.contract_type,
  ${SQL_CONTRACT_IMPORT_STATUS}                AS gr_import_status,
  ${backlogInactive}                           AS backlog_blocked_by_gr_status,
  c.status,
  c.contract_date,
  c.plant_code,
  c.product
FROM contracts c
WHERE TRIM(c.po_number::text) = TRIM(:'po') OR TRIM(c.contract_id::text) = TRIM(:'po');

\\echo '=== 2. shipments on this contract (execution path) ==='
SELECT
  s.id,
  s.shipment_id,
  s.operation_id,
  s.status,
  s.vessel_name,
  s.created_at
FROM shipments s
JOIN contracts c ON c.id = s.contract_id
WHERE TRIM(c.po_number::text) = TRIM(:'po') OR TRIM(c.contract_id::text) = TRIM(:'po')
ORDER BY s.created_at;

\\echo '=== 3. backlog path gates (only relevant when section 2 is empty) ==='
SELECT
  EXISTS (SELECT 1 FROM shipments s_ns WHERE s_ns.contract_id = c.id) AS has_shipment_row,
  ${sharesSto}                                 AS blocked_by_sibling_sto,
  ${backlogInactive}                           AS blocked_by_gr_status
FROM contracts c
WHERE TRIM(c.po_number::text) = TRIM(:'po') OR TRIM(c.contract_id::text) = TRIM(:'po');

\\echo '=== 4. STO rows ==='
SELECT cs.sto_number, cs.sto_type, cs.updated_at
FROM contract_stos cs
JOIN contracts c ON c.id = cs.contract_id
WHERE TRIM(c.po_number::text) = TRIM(:'po') OR TRIM(c.contract_id::text) = TRIM(:'po')
ORDER BY cs.sto_number;

\\echo '=== 5. latest SAP row for this PO ==='
SELECT
  spd.contract_number,
  spd.created_at,
  spd.data->'raw'->>'Incoterm'                 AS raw_incoterm,
  spd.data->'raw'->>'STO Type'                 AS raw_sto_type,
  spd.data->'raw'->>'STO No.'                  AS raw_sto_no,
  spd.data->'raw'->>'B2B Flag'                 AS raw_b2b_flag,
  spd.data->'raw'->>'Contract Reference PO'    AS raw_contract_ref_po,
  spd.data->'raw'->>'Discharge Destination'    AS raw_discharge_destination
FROM sap_processed_data spd
WHERE TRIM(spd.contract_number) IN (
  SELECT TRIM(c.contract_id::text) FROM contracts c
  WHERE TRIM(c.po_number::text) = TRIM(:'po') OR TRIM(c.contract_id::text) = TRIM(:'po')
)
ORDER BY spd.created_at DESC
LIMIT 3;

\\echo '=== 6. snapshot freshness (can hide a row on status-filtered views only) ==='
SELECT module, is_stale, refreshed_at, row_count FROM pipeline_summary_refresh_meta ORDER BY module;
SELECT 'contract_latest_spd' AS meta, is_stale, refreshed_at FROM contract_latest_spd_snapshot_meta WHERE id = 'global';

\\echo '=== 7. how many contracts share this PO number ==='
SELECT COUNT(*)::int AS contracts_with_this_po
FROM contracts c
WHERE TRIM(c.po_number::text) = TRIM(:'po');
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, sql, 'utf8');
// eslint-disable-next-line no-console
console.log(`wrote ${OUT} (${(sql.length / 1024).toFixed(1)} KB)`);
