-- GENERATED by backend/src/scripts/renderWbMigrationExportSql.ts - do not edit by hand.
--
-- Wave 1 export: WB daily actuals that are safe to carry to production.
--
-- Emits CSV on stdout. Read-only.
--
-- Carried only when every one of these holds, and each is a rule the application itself already
-- applies - none of it is invented here:
--   * the operation is not a soft-deduped loser        (migration 137, deduped_at)
--   * the operation is not cancelled                   (excluded from matching everywhere)
--   * its contract has a PO number                     (migration 119 identity; without it the
--                                                       row cannot be re-anchored in production)
--   * the contract is FRC/LCO and not SEA              (trucking page scope, migration 077)
--   * the row is not a blank-STO row shadowed by
--     per-STO rows for the same operation and date     (migration 124 - these double-counted)
--   * it carries at least one non-negative quantity
COPY (
  SELECT
    TRIM(c.po_number::text)                                  AS po_number,
    TRIM(c.contract_id::text)                                AS contract_number,
    COALESCE(NULLIF(TRIM(d.sto_number), ''), '')             AS sto_number,
    d.progress_date::date                                    AS progress_date,
    d.quantity_kg,
    d.quantity_delivery_kg,
    d.quantity_receive_kg,
    COALESCE(d.source, '')                                   AS source
  FROM trucking_daily_actuals d
  INNER JOIN trucking_operations t ON t.id = d.trucking_operation_id
  INNER JOIN contracts c           ON c.id = t.contract_id
  WHERE t.deduped_at IS NULL
    AND UPPER(COALESCE(t.status, '')) NOT IN ('CANCELLED', 'CANCELED')
    AND NULLIF(TRIM(c.po_number::text), '') IS NOT NULL
    AND UPPER(TRIM(COALESCE(
    NULLIF(TRIM(c.incoterm), ''),
    (
      SELECT COALESCE(
        spd.data->'contract'->>'incoterm',
        spd.data->'raw'->>'Incoterm',
        spd.data->>'Incoterm'
      )
      FROM sap_processed_data spd
      WHERE TRIM(spd.contract_number) = TRIM((c).contract_id::text)
      ORDER BY spd.created_at DESC NULLS LAST
      LIMIT 1
    ),
    ''
  ))) IN ('FRC', 'LCO')
    AND UPPER(COALESCE(NULLIF(TRIM(c.transport_mode), ''), '')) <> 'SEA'
    AND NOT (
      NULLIF(TRIM(COALESCE(d.sto_number, '')), '') IS NULL
      AND EXISTS (
        SELECT 1 FROM trucking_daily_actuals d2
        WHERE d2.trucking_operation_id = d.trucking_operation_id
          AND d2.progress_date = d.progress_date
          AND NULLIF(TRIM(COALESCE(d2.sto_number, '')), '') IS NOT NULL
      )
    )
    AND COALESCE(d.quantity_kg, 0) >= 0
    AND COALESCE(d.quantity_delivery_kg, 0) >= 0
    AND COALESCE(d.quantity_receive_kg, 0) >= 0
    AND (d.quantity_kg IS NOT NULL OR d.quantity_delivery_kg IS NOT NULL OR d.quantity_receive_kg IS NOT NULL)
  ORDER BY 1, 3, 4
) TO STDOUT WITH CSV HEADER;
