-- GENERATED by backend/src/scripts/renderEtaPlanningExportSql.ts - do not edit by hand.
--
-- Wave 2a export: vessel ETA, at both the port and the shipment grain.
--
-- Emits CSV on stdout. Read-only.
--
-- SAP never supplies ETA (0 occurrences across 27,003 SAP rows), so every value here is user
-- input that production cannot recreate.
COPY (
  -- Port-level ETA. port_sequence + is_discharge_port is how the application matches a port row.
  SELECT
    'port'                                        AS scope,
    TRIM(c.po_number::text)                       AS po_number,
    TRIM(c.contract_id::text)                     AS contract_number,
    COALESCE(NULLIF(TRIM(s.shipment_id), ''), '') AS shipment_key,
    vlp.port_sequence                             AS port_sequence,
    COALESCE(vlp.is_discharge_port, FALSE)        AS is_discharge_port,
    COALESCE(NULLIF(TRIM(vlp.port_name), ''), '') AS port_name,
    vlp.eta_vessel_arrival,
    vlp.eta_vessel_berthed,
    vlp.eta_loading_start,
    vlp.eta_loading_completed,
    vlp.eta_vessel_sailed,
    vlp.eta_vessel_berthed_at_loading_port,
    vlp.eta_vessel_arrive_at_discharge_port,
    vlp.eta_vessel_berthed_at_discharge_port,
    vlp.eta_vessel_start_discharging,
    vlp.eta_vessel_complete_discharge,
    NULL::numeric AS sfal_qty,
    NULL::numeric AS sfbd_qty
  FROM vessel_loading_ports vlp
  INNER JOIN shipments s ON s.id = vlp.shipment_id
  INNER JOIN contracts c ON c.id = s.contract_id
  WHERE NULLIF(TRIM(c.po_number::text), '') IS NOT NULL
    AND UPPER(COALESCE(s.status, '')) NOT IN ('CANCELLED', 'CANCELED')
    AND COALESCE(
      vlp.eta_vessel_arrival, vlp.eta_vessel_berthed, vlp.eta_loading_start,
      vlp.eta_loading_completed, vlp.eta_vessel_sailed,
      vlp.eta_vessel_berthed_at_loading_port, vlp.eta_vessel_arrive_at_discharge_port,
      vlp.eta_vessel_berthed_at_discharge_port, vlp.eta_vessel_start_discharging,
      vlp.eta_vessel_complete_discharge
    ) IS NOT NULL

  UNION ALL

  -- Shipment-level ETA. NULL port_sequence marks the grain; the loader writes shipments.eta_*.
  SELECT
    'shipment'                                    AS scope,
    TRIM(c.po_number::text)                       AS po_number,
    TRIM(c.contract_id::text)                     AS contract_number,
    COALESCE(NULLIF(TRIM(s.shipment_id), ''), '') AS shipment_key,
    NULL::int                                     AS port_sequence,
    FALSE                                         AS is_discharge_port,
    ''                                            AS port_name,
    s.eta_arrival,
    s.eta_berthed,
    s.eta_loading_start,
    s.eta_loading_complete,
    s.eta_sailed,
    NULL::timestamp,
    s.eta_discharge_arrival,
    s.eta_discharge_berthed,
    s.eta_discharge_start,
    s.eta_discharge_complete,
    s.sfal_qty,
    s.sfbd_qty
  FROM shipments s
  INNER JOIN contracts c ON c.id = s.contract_id
  WHERE NULLIF(TRIM(c.po_number::text), '') IS NOT NULL
    AND UPPER(COALESCE(s.status, '')) NOT IN ('CANCELLED', 'CANCELED')
    AND (
      COALESCE(
        s.eta_arrival, s.eta_berthed, s.eta_loading_start, s.eta_loading_complete, s.eta_sailed,
        s.eta_discharge_arrival, s.eta_discharge_berthed, s.eta_discharge_start,
        s.eta_discharge_complete
      ) IS NOT NULL
      -- SFAL/SFBD are carried on the same row and are KLIP-only in their own right, so a shipment
      -- holding only those still has something worth migrating.
      OR s.sfal_qty IS NOT NULL OR s.sfbd_qty IS NOT NULL
    )

  ORDER BY 2, 1, 5 NULLS FIRST, 6
) TO STDOUT WITH CSV HEADER;
