-- GENERATED by backend/src/scripts/renderEtaPlanningExportSql.ts - do not edit by hand.
--
-- Wave 2b export: trucking daily planning.
--
-- Emits CSV on stdout. Read-only.
--
-- SAP has no writer for daily_deliverables, so a plan is proof of KLIP authorship on its own -
-- no provenance argument is needed, unlike the ATA and quantity columns.
COPY (
  SELECT
    TRIM(c.po_number::text)                       AS po_number,
    TRIM(c.contract_id::text)                     AS contract_number,
    t.daily_deliverables::text                    AS daily_deliverables,
    t.last_daily_deliverable_date,
    t.trucking_start_date,
    t.trucking_completion_date,
    t.sfal_qty,
    t.sfbd_qty
  FROM trucking_operations t
  INNER JOIN contracts c ON c.id = t.contract_id
  WHERE t.deduped_at IS NULL
    AND UPPER(COALESCE(t.status, '')) NOT IN ('CANCELLED', 'CANCELED')
    AND NULLIF(TRIM(c.po_number::text), '') IS NOT NULL
    AND (
      jsonb_array_length(COALESCE(NULLIF(t.daily_deliverables, 'null'::jsonb), '[]'::jsonb)) > 0
      -- SFAL/SFBD on trucking are KLIP-only (migration 148 has no SAP writer), so an operation
      -- carrying only those is still worth migrating.
      OR t.sfal_qty IS NOT NULL OR t.sfbd_qty IS NOT NULL
    )
  ORDER BY 1
) TO STDOUT WITH CSV HEADER;
