-- Master Vessel identity: a KLIP-owned code, and a namespace on every alias code.
--
-- Asked by Ryan on 2026-09-23, ahead of the DHM integration and a later jetty planning system.
-- Today `master_vessels.vessel_code` is not a KLIP code at all - it is whichever code arrived
-- first, chosen in masterVesselCodeResolve.ts by the order Jovin -> KLIP sheet -> SAP -> existing
-- row, and when nothing is known a `TMP-<name>` slug is invented. Measured on a copy of
-- production: 295 of 474 vessels carry a TMP- code, and displayVesselCode() hides those, so 62%
-- of the master shows a blank Vessel Code in the UI.
--
-- Two columns fix that, and neither is read by anything yet - this migration is additive.
--
-- 1. vessel_code_klip (KVSL-0001)
--    A code KLIP owns, generated by the database so no write path can produce a row without one.
--    master_vessels is written from four directions - SAP import, Jovin import, the DHM webhook
--    and the edit modal - and a generator in TypeScript would eventually be missed by one of
--    them. The code encodes nothing: vessel names will start syncing from DHM, so a code derived
--    from the name would have to change when the name does, which is exactly what a system code
--    exists to avoid. TMP- already demonstrated the failure - because the name was in the code,
--    the code was treated as temporary and hidden.
--
-- 2. master_vessel_code_aliases.namespace
--    The alias table already holds many codes per vessel and already resolves 2,101 of 2,101
--    shipment vessel codes. What it cannot do is answer "which of these is the SAP code", and
--    that is the question PO->vessel mapping asks. `source` cannot answer it: it records where a
--    code was first seen, not which system owns it, and source='db_existing' holds 84 real SAP
--    codes alongside 382 non-SAP ones.
--
--    Backfilled here only from what the database itself can prove - a code seen in
--    sap_processed_data is SAP, a TMP- slug is KLIP, everything else is LEGACY. The 49 codes that
--    appear in the cleanup workbook but not yet in any transaction are promoted to SAP by
--    scripts/cleanseMasterVesselFromWorkbook.ts, which can read that workbook.
--
-- 3. One primary alias per vessel
--    563 aliases are flagged is_primary across 474 vessels, and 89 vessels carry more than one.
--    Nothing can rely on "the primary code" until that is true, so this collapses it to one -
--    preferring the alias that equals master_vessels.vessel_code, then the oldest row.

-- 1. KLIP-owned code -------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS master_vessel_klip_code_seq;

ALTER TABLE master_vessels
  ADD COLUMN IF NOT EXISTS vessel_code_klip VARCHAR(20);

-- Backfill in a stable order so a re-run of this migration on another environment is at least
-- self-consistent. lpad only pads, so passing 9,999 widens the code rather than truncating it.
UPDATE master_vessels mv
SET vessel_code_klip = 'KVSL-' || lpad(seq.n::text, 4, '0')
FROM (
  SELECT id, nextval('master_vessel_klip_code_seq') AS n
  FROM (
    SELECT id FROM master_vessels
    WHERE vessel_code_klip IS NULL
    ORDER BY created_at NULLS LAST, id
  ) ordered
) seq
WHERE mv.id = seq.id;

ALTER TABLE master_vessels
  ALTER COLUMN vessel_code_klip
  SET DEFAULT ('KVSL-' || lpad(nextval('master_vessel_klip_code_seq')::text, 4, '0'));

ALTER TABLE master_vessels
  ALTER COLUMN vessel_code_klip SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_master_vessels_vessel_code_klip
  ON master_vessels (vessel_code_klip);

-- 2. Namespace on alias codes ----------------------------------------------------------------
ALTER TABLE master_vessel_code_aliases
  ADD COLUMN IF NOT EXISTS namespace VARCHAR(10) NOT NULL DEFAULT 'LEGACY';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'chk_master_vessel_code_aliases_namespace'
  ) THEN
    ALTER TABLE master_vessel_code_aliases
      ADD CONSTRAINT chk_master_vessel_code_aliases_namespace
      CHECK (namespace IN ('SAP', 'KLIP', 'DHM', 'LEGACY'));
  END IF;
END $$;

UPDATE master_vessel_code_aliases
SET namespace = 'KLIP'
WHERE namespace = 'LEGACY'
  AND upper(trim(vessel_code)) LIKE 'TMP-%';

UPDATE master_vessel_code_aliases a
SET namespace = 'SAP'
WHERE a.namespace = 'LEGACY'
  AND EXISTS (
    SELECT 1
    FROM sap_processed_data spd
    WHERE upper(trim(COALESCE(
          spd.data->'shipment'->>'vessel_code',
          spd.data->'vessel'->>'vessel_code',
          spd.data->'raw'->>'Vessel Code'
        ))) = upper(trim(a.vessel_code))
  );

CREATE INDEX IF NOT EXISTS idx_master_vessel_code_aliases_namespace
  ON master_vessel_code_aliases (namespace, master_vessel_id);

-- 3. Exactly one primary alias per vessel ----------------------------------------------------
WITH ranked AS (
  SELECT a.id,
         row_number() OVER (
           PARTITION BY a.master_vessel_id
           ORDER BY
             CASE WHEN upper(trim(a.vessel_code)) = upper(trim(mv.vessel_code)) THEN 0 ELSE 1 END,
             CASE WHEN a.is_primary THEN 0 ELSE 1 END,
             a.created_at NULLS LAST,
             a.id
         ) AS rn
  FROM master_vessel_code_aliases a
  INNER JOIN master_vessels mv ON mv.id = a.master_vessel_id
)
-- Demote first. The unique index is checked per row, so promoting the new primary before the old
-- one is cleared trips it mid-statement.
UPDATE master_vessel_code_aliases a
SET is_primary = false, updated_at = CURRENT_TIMESTAMP
FROM ranked
WHERE a.id = ranked.id AND ranked.rn > 1 AND a.is_primary;

WITH ranked AS (
  SELECT a.id,
         row_number() OVER (
           PARTITION BY a.master_vessel_id
           ORDER BY
             CASE WHEN upper(trim(a.vessel_code)) = upper(trim(mv.vessel_code)) THEN 0 ELSE 1 END,
             CASE WHEN a.is_primary THEN 0 ELSE 1 END,
             a.created_at NULLS LAST,
             a.id
         ) AS rn
  FROM master_vessel_code_aliases a
  INNER JOIN master_vessels mv ON mv.id = a.master_vessel_id
)
UPDATE master_vessel_code_aliases a
SET is_primary = true, updated_at = CURRENT_TIMESTAMP
FROM ranked
WHERE a.id = ranked.id AND ranked.rn = 1 AND NOT a.is_primary;

CREATE UNIQUE INDEX IF NOT EXISTS uq_master_vessel_code_aliases_one_primary
  ON master_vessel_code_aliases (master_vessel_id)
  WHERE is_primary;
