-- Reload Master Plant from docs/Master Data - CPO 28 Sep 2026.xlsx, sheet Internal Company.
-- A row is kept only when Company Name, Site, and Plant Code are filled.
-- site_id is set when that site still exists on Master Site.

DELETE FROM master_plants;

SELECT setval('master_plant_klip_code_seq', 1, false);

INSERT INTO master_plants (
  company_code, company_name, plant_code, plant_name, plant_type, site, city, postal_code, found_in
) VALUES
('BN', 'PT KPBN', 'BN10', 'KPBN TRADING PLANT', 'HO TRADING', 'PROBOLINGGO', 'DKI JAKARTA', '10330', 'SAP & DWS'),
('CD', 'PT. CISADANE RAYA CHEMICALS', 'CD21', 'CRC OLEO CHEMICAL TANGERANG', 'MILL PROCESS', 'TANGERANG', 'TANGERANG', '15115', 'SAP & DWS'),
('CD', 'PT. CISADANE RAYA CHEMICALS', 'CD2A', 'CRC REFINERY TANGERANG', 'MILL PROCESS', 'TANGERANG', 'BOJONG JAYA KARAWACI, BANTEN', '15115', 'SAP & DWS'),
('EO', 'PT. ENERGI OLEO PERSADA', 'EO10', 'EOP TRADING PLANT', 'HO TRADING', 'BONTANG', 'DKI JAKARTA', '12940', 'SAP & DWS'),
('EO', 'PT. ENERGI OLEO PERSADA', 'EO21', 'EOP GENERAL TJ. MORAWA', 'MILL PROCESS', 'TANJUNG MORAWA', 'TANJUNG MORAWA', '20362', 'SAP & DWS'),
('EO', 'PT. ENERGI OLEO PERSADA', 'EO22', 'EOP GENERAL BELAWAN', 'MILL PROCESS', 'TANJUNG MORAWA', 'TANJUNG MORAWA', '20411', 'SAP & DWS'),
('EO', 'PT. ENERGI OLEO PERSADA', 'EO2A', 'EOP REFINERY TJ.MORAWA', 'MILL PROCESS', 'TANJUNG MORAWA', 'TJ. MORAWA', '20362', 'SAP & DWS'),
('EU', 'EUP TRADING PLANT', 'EU10', 'EUP TRADING PLANT', 'HO TRADING', 'KARAWANG', 'DKI JAKARTA', '12980', 'SAP & DWS'),
('EU', 'EUP EDIBLE OIL L.GAUNG', 'EU21', 'EUP EDIBLE OIL LUBUK GAUNG', 'MILL PROCESS', 'LUBUK GAUNG', 'DUMAI', '28826', 'SAP & DWS'),
('EU', 'EUP EDIBLE OIL BONTANG', 'EU22', 'EUP EDIBLE OIL BONTANG', 'MILL PROCESS', 'BONTANG', 'BONTANG', '75325', 'SAP & DWS'),
('EU', 'EUP EDIBLE OIL TJ.PURA', 'EU23', 'EUP EDIBLE OIL TJ.PURA', 'MILL PROCESS', 'TANJUNG PURA', 'TANJUNG PURA', '78371', 'SAP & DWS'),
('EU', 'EUP EDIBLE OIL BATAM', 'EU26', 'EUP EDIBLE OIL BATAM', 'MILL PROCESS', 'BATAM', 'BATAM', '29444', 'SAP & DWS'),
('EU', 'EUP BIOMASS LUBUK GAUNG', 'EU51', 'EUP BIOMASS LUBUK GAUNG', 'SPECIAL MILL PROCESS', 'LUBUK GAUNG', 'DUMAI', '28826', 'SAP & DWS'),
('EU', 'EUP BIOMASS BONTANG', 'EU52', 'EUP BIOMASS BONTANG', 'SPECIAL MILL PROCESS', 'BONTANG', 'BONTANG', '75325', 'SAP & DWS'),
('EU', 'EUP BIOMASS TJ.PURA', 'EU53', 'EUP BIOMASS TJ.PURA', 'SPECIAL MILL PROCESS', 'TANJUNG PURA', 'TANJUNG PURA', '78371', 'SAP & DWS'),
('EU', 'EUP BIOMASS KUMAI', 'EU54', 'EUP BIOMASS KUMAI', 'SPECIAL MILL PROCESS', 'KUMAI', 'KUMAI', '74181', 'SAP & DWS'),
('EU', 'EUP BIOMASS PALEMBANG', 'EU55', 'EUP BIOMASS PALEMBANG', 'SPECIAL MILL PROCESS', 'PALEMBANG', 'PALEMBANG', '30961', 'SAP & DWS'),
('GM', 'GLM EDIBLE OIL SELANGOR', 'GM21', 'GLM REFINERY PORT KLANG', 'MILL PROCESS', 'SELANGOR', 'PORT KLANG FREE ZONE MALAYSIA', '42920', 'SAP & DWS'),
('JP', 'JPN TRADING PLANT', 'JP10', 'JPN TRADING PLANT', 'HO TRADING', 'TANGERANG', 'DKI JAKARTA', '12980', 'SAP & DWS'),
('JP', 'JPN GENERAL SIDOARJO', 'JP22', 'JPN ANIMAL FEED SIDOARJO', 'MILL PROCESS', 'SIDOARJO', 'SIDOARJO', NULL, 'SAP & DWS'),
('JP', 'PT. JATI PERKASA NUSANTARA', 'JP26', 'JPN ANIMAL FEED GRESIK', 'MILL PROCESS', 'GRESIK', 'GRESIK', '61119', 'SAP & DWS'),
('PM', 'PMC BIOENERGY LB.GAUNG', 'PM21', 'PMC BIOENERGY LB.GAUNG', 'BIOENERGY', 'LUBUK GAUNG', 'DUMAI', '28826', 'SAP & DWS'),
('PS', 'PRC TRADING PLANT', 'PS10', 'PRISCOLIN TRADING PLANT', 'HO TRADING', 'KARAWANG', 'DKI JAKARTA', '12980', 'SAP & DWS'),
('PS', 'PRC GENERAL BEKASI', 'PS21', 'PRC PALM & LAURIC BEKASI', 'MILL PROCESS', 'BEKASI', 'BEKASI', '17131', 'SAP & DWS'),
('PS', 'PRC GENERAL KARAWANG', 'PS23', 'PRC PALM & LAURIC KARAWANG', 'MILL PROCESS', 'KARAWANG', 'KARAWANG', '41361', 'SAP & DWS'),
('RB', 'PT RIAU SEMESTA BIOMASSA', 'RB10', 'RSB TRADING PLANT', 'HO TRADING', 'RIAU', 'DKI JAKARTA', '10350', 'SAP & DWS'),
('RB', 'PT RIAU SEMESTA BIOMASSA', 'RB21', 'RSB BIOMASS TJ.BUTON', 'MILL PROCESS', 'TANJUNG BUTON', 'PEKAN BARU', '28662', 'SAP & DWS'),
('RI', 'RFI GENERAL BEKASI', 'RI21', 'RFI GENERAL BEKASI', 'MILL PROCESS', 'BEKASI', 'BEKASI', '17131', 'SAP & DWS'),
('SC', 'SPC TRADING PLANT', 'SC10', 'SPC TRADING PLANT', 'HO TRADING', 'LUBUK GAUNG', 'JAKARTA', '12980', 'SAP & DWS'),
('SC', 'SPC PALM & LAURIC LB.GAUNG', 'SC22', 'SPC PALM & LAURIC LB.GAUNG', 'MILL PROCESS', 'LUBUK GAUNG', 'DUMAI', '28826', 'SAP & DWS'),
('TP', 'TPG EDIBLE OIL TJ.LANGSAT', 'TP21', 'TPG PALM & LAURIC TJ.LANGSAT', 'MILL PROCESS', 'PASIR GUDANG', 'JOHOR BAHRU MALAYSIA', '81700', 'SAP & DWS');

UPDATE master_plants AS plant
SET site_id = site.id
FROM master_sites AS site
WHERE upper(trim(plant.site)) = upper(trim(site.site_name));
