/** Hover help for calculated / business-logic fields (Contracts, Dashboard, etc.) */

export const FIELD_HELP = {
  contractAging: `Days from today to Due Date Delivery End (or delivery window). Overdue shows in red when past the end date.`,

  overUnderDelivery: `When contract status is Close: compares Outstanding Quantity vs 0 — "Over Delivery" when outstanding < 0, "Under Delivery" when outstanding > 0, or "Passed" when outstanding = 0. Open contracts show "-".`,

  logCycle: `Land: Cargo Readiness Date → latest Trucking Last Receive (Close) or today (Open). SEA: Cargo Readiness Date → latest ATA Vessel Complete Discharge (Close) or today (Open).`,

  tradeCycle: `Open: today → Due Date Delivery End. Closed: latest receive/discharge → Due Date Delivery End (Land: Trucking Last Receive; SEA: ATA Vessel Complete Discharge).`,

  cashCycle: `Closed only: latest receive/discharge → Payoff Date (Land: Trucking Last Receive; SEA: ATA Vessel Complete Discharge).`,

  outstandingQty: `Contract Quantity minus Total STO Quantity from SAP (can be negative if overshipped).`,

  companyName: `From Buyer in latest SAP data. For B2B "origin" contracts (empty Contract Reff PO), Company Name may follow linked B2B child contracts per business rules.`,

  b2bParties: `Lists contracts whose Contract Reff PO Ini matches this contract's PO Number.`,

  aiInsight: `Generated by Gemini using aggregated metrics for the filters you selected. Cached per filter combination; use Re-generate to refresh.`,

  dashboardKpiContracts: `Counts and closure mix use contracts in scope of your current dashboard filters (date, plant, supplier, product, group).`,
  dashboardKpiQuantity: `Quantity KPIs use contract ordered vs SAP delivered quantities; outstanding payment uses contracts with at least one blank payoff date, aligned with Quantity Performance logic.`,

  dashboardKpiShipments: `Shipment counts and late rate are based on shipments matching the same dashboard filters.`,

  dashboardKpiTrucking: `Trucking operation counts and completion/late metrics use trucking data in filter scope.`,

  dashboardKpiFinance: `Payment totals and overdue amounts aggregate payments linked to contracts in filter scope.`,

  // Trucking
  lateIndicator: `On Time / Late is calculated by comparing actual dates vs ETA/Due Date (when available). If required dates are missing, this shows "-".`,
  gainLossPct: `Calculated as (Delivered - Sent) / Sent × 100%. Positive means gain, negative means loss.`,
  gainLossAmount: `Calculated as Delivered - Sent (in Kg). Positive means gain, negative means loss.`,
  truckingOaBudget: `OA Budget is the planned operational allowance (budget) for the trucking leg.`,
  truckingOaActual: `OA Actual is the realized operational allowance (actual cost) for the trucking leg.`,
  etaVsDueDelivery: `ETA fields are planned dates; Due Date Delivery Start/End come from the contract delivery window. Use these to assess schedule risk and lateness.`,

  // Shipments
  shipmentLateIndicator: `On Time / Late is based on SLA days and actual vessel milestone dates. If key dates are missing, this shows "-".`,
  shipmentSlaDays: `SLA Days is the target duration for the shipment/leg. Used to flag delayed shipments when actual duration exceeds SLA.`,
  vesselOaBudget: `Vessel OA Budget is the planned operational allowance (budget) for the vessel/shipment leg.`,
  vesselOaActual: `Vessel OA Actual is the realized operational allowance (actual cost) for the vessel/shipment leg.`,

  // Finance
  financeTotalAmount: `Total Amount is the sum of payment_amount across the current finance dataset (subject to any page filters).`,
  financePendingAmount: `Pending Amount includes payments that are not marked paid yet (awaiting confirmation).`,
  financePaidAmount: `Paid Amount includes payments with status PAID.`,
  financeOverdueAmount: `Overdue Amount includes payments past Payment Due Date that are not fully paid.`,
  dueDatePayment: `Payment Due Date is the contractual/latest due date used to determine overdue status.`,
  dpDate: `DP Date is the down payment date (if applicable).`,
  payoffDate: `Payoff Date is the final payoff date; blank payoff date is commonly used to indicate outstanding payment in dashboard logic.`,
  dpDeviationDays: `DP deviation (days) = DP Date - Due Date Payment (in days). Positive means DP happened after due date.`,
  payoffDeviationDays: `Payoff deviation (days) = Payoff Date - Due Date Payment (in days). Positive means payoff happened after due date.`,
} as const

export type FieldHelpKey = keyof typeof FIELD_HELP
