/** Hover help for calculated / business-logic fields (Contracts, Dashboard, etc.) */

export const FIELD_HELP = {
  contractAging: `Days from today to Due Date Delivery End (or delivery window). Overdue shows in red when past the end date.`,

  overUnderDelivery: `When contract status is Close: compares Total STO Quantity vs Contract Quantity — "Over Delivery", "Under Delivery", or "Passed" if equal. Open contracts show "-".`,

  logCycle: `Land: earliest Trucking Start Receive → latest Trucking Last Receive (Close) or today (Open). SEA: earliest ATA Vessel Completed Loading → latest ATA Discharge Complete (Close) or today (Open). Aggregated across all STOs/operations for the contract.`,

  tradeCycle: `Uses DP Date vs today (Open) or vs latest receive/discharge date (Close) depending on Land vs SEA rules.`,

  outstandingQty: `Contract Quantity minus Total STO Quantity from SAP (can be negative if overshipped).`,

  companyName: `From Buyer in latest SAP data. For B2B "origin" contracts (empty Contract Reff PO), Company Name may follow linked B2B child contracts per business rules.`,

  b2bParties: `Lists contracts whose Contract Reff PO Ini matches this contract's PO Number.`,

  aiInsight: `Generated by Gemini using aggregated metrics for the filters you selected. Cached per filter combination; use Re-generate to refresh.`,

  dashboardKpiContracts: `Counts and closure mix use contracts in scope of your current dashboard filters (date, plant, supplier, product, group).`,

  dashboardKpiShipments: `Shipment counts and late rate are based on shipments matching the same dashboard filters.`,

  dashboardKpiTrucking: `Trucking operation counts and completion/late metrics use trucking data in filter scope.`,

  dashboardKpiFinance: `Payment totals and overdue amounts aggregate payments linked to contracts in filter scope.`,
} as const

export type FieldHelpKey = keyof typeof FIELD_HELP
