/** Hover help for calculated / business-logic fields (Contracts, Dashboard, etc.) */

export const FIELD_HELP = {
  contractAging: `Days from today to Due Date Delivery End (or delivery window). Overdue shows in red when past the end date.`,

  /** Matches `showUrgentFlag` in contracts/page.tsx */
  contractUrgentFlag: `Red flag when the contract is within the delivery window and expected logistics rows are still missing.

• Due Date Delivery Start must be set; otherwise no flag.
• Shown only when that start date is in 14 days or less from today (includes overdue starts).
• SEA: flag if there are no shipments and no STOs (both counts zero).
• LAND: flag if there is no trucking (count zero).
• MIX: flag if shipments/STOs are missing OR trucking is missing.
• Other transport modes: flag only if both shipments/STOs and trucking are missing.`,

  overUnderDelivery: `When contract status is Close: compares Outstanding Quantity vs 0 — "Over Delivery" when outstanding < 0, "Under Delivery" when outstanding > 0, or "Passed" when outstanding = 0. Open contracts show "-".`,

  logCycle: `Land: Cargo Readiness → Trucking Last Receive (Close) or Open completion end. SEA: Cargo Readiness → ATA Vessel Complete Discharge (Close) or Open completion end. Open: today only when standard ETA is empty; if standard ETA exists, completion date is required (no today substitute).`,

  tradeCycle: `Closed: completion receive/discharge → Due Date Delivery End. Open Condition A (standard ETA set): completion planning/discharge → due end. Open Condition B (standard ETA empty): today → due end. Trade cycle ≤ 0 counts as on time for Section 2/3 (Condition A); Condition B treats 0 days as late.`,

  statusCardAvgDp: `Average DP Cycle (days) for Open or Close contracts in scope. Only contracts with a valid SAP DP Date and computable cycle are included; if none qualify, the card shows "- days" (not 0 days).`,

  statusCardAvgLog: `Average Log Cycle (days) for Open or Close contracts in scope. Only contracts with cargo readiness and a valid completion end are included; if none qualify, the card shows "- days" (not 0 days).`,

  cashCycle: `Requires SAP Payoff Date (no payments-table fallback). Closed: completion receive/discharge → Payoff. Open: Payoff → completion end; if standard ETA is empty, completion end is today; if standard ETA exists, completion end must be planning/discharge (no today substitute). Missing Payoff or completion → no value.`,

  dpCycle: `Requires SAP DP Date (no payments-table fallback). Closed: completion receive/discharge → DP Date. Open: DP Date → completion end (same Open ETA/today rules as Cash Cycle). Missing DP or completion → no value.`,

  outstandingQty: `Remaining quantity yet to be delivered. Green = Over Delivered; Red = Still Outstanding.`,

  receivedQty: `Actual quantity received based on contract data (quantity_receive). For sea shipments: received at destination. For land shipments: quantity delivered to plant/site.`,

  outstandingQtyMt: `Remaining quantity yet to be delivered (in MT). Green = Over Delivered; Red = Still Outstanding.`,

  companyName: `From Buyer in latest SAP data. For B2B "origin" contracts (empty Contract Reff PO), Company Name may follow linked B2B child contracts per business rules.`,

  b2bParties: `Lists contracts whose Contract Reff PO Ini matches this contract's PO Number.`,

  aiInsight: `Generated by Gemini using aggregated metrics for the filters you selected. Cached per filter combination; use Re-generate to refresh.`,

  dashboardKpiContracts: `Counts and closure mix use contracts in scope of your current dashboard filters (date, plant, supplier, product, group).`,
  dashboardKpiQuantity: `Quantity KPIs use contract ordered vs SAP delivered quantities; outstanding payment uses contracts with at least one blank payoff date, aligned with Quantity Performance logic.`,

  dashboardKpiShipments: `Shipment counts and late rate are based on shipments matching the same dashboard filters.`,

  dashboardKpiTrucking: `Trucking operation counts and completion/late metrics use trucking data in filter scope.`,

  dashboardKpiFinance: `Payment totals and overdue amounts aggregate payments linked to contracts in filter scope.`,

  // Trucking
  lateIndicator: `On Time / Late is calculated by comparing actual dates vs ETA/Due Date (when available). If required dates are missing, this shows "-".`,
  gainLossPct: `Calculated as (Delivered - Sent) / Sent × 100%. Positive means gain, negative means loss.`,
  gainLossAmount: `Calculated as Delivered - Sent (in Kg). Positive means gain, negative means loss.`,
  truckingOaBudget: `OA Budget is the planned operational allowance (budget) for the trucking leg.`,
  truckingOaActual: `OA Actual is the realized operational allowance (actual cost) for the trucking leg.`,
  etaVsDueDelivery: `ETA fields are planned dates; Due Date Delivery Start/End come from the contract delivery window. Use these to assess schedule risk and lateness.`,
  truckingStatusPlanned: `No Trucking Start Receive Date yet (from SAP or manual entry). The operation is open and waiting to begin the land leg.`,
  truckingStatusInProgress: `Trucking Start Receive Date is set and Trucking Last Receive Date is still empty. SAP column AV maps to trucking start; status IN_PROGRESS.`,
  truckingStatusCompleted: `Trucking Last Receive Date is set (SAP column AW, stored as trucking completion date). The land delivery leg is finished for this operation.`,
  truckingStatusCancelled: `Operation was set to Cancelled manually and is excluded from active execution. Use the Status filter below to view cancelled operations only.`,

  // Shipping Performance
  shipmentTotalDelta: `Sum of all delay gaps in days: (Loading ETA−ETR) + (Loading ETA−ETB) + (Loading ETB−ETC) + (Discharge ETA−ETB) + (Discharge ETB−ETC). Positive = late, negative = ahead of schedule.`,

  shipmentStoQty: `STO Quantity from the linked contract in SAP (in MT). Represents the planned quantity allocated to this shipment.`,
  shipmentReceivedQty: `Actual quantity received at destination (actual_vessel_qty_receive or BL quantity as fallback), in MT.`,
  shipmentOutstandingQty: `SAP STO Qty minus Qty Receive/Delivered (per incoterm) for this shipment/STO. Same for Open and Close; Close = status COMPLETED.`,

  // Shipments
  shipmentLateIndicator: `On Time / Late is based on SLA days and actual vessel milestone dates. If key dates are missing, this shows "-".`,
  shipmentSlaDays: `SLA Days is the target duration for the shipment/leg. Used to flag delayed shipments when actual duration exceeds SLA.`,
  vesselOaBudget: `Vessel OA Budget is the planned operational allowance (budget) for the vessel/shipment leg.`,
  vesselOaActual: `Vessel OA Actual is the realized operational allowance (actual cost) for the vessel/shipment leg.`,

  // Finance
  financeTotalAmount: `Total Amount is the sum of payment_amount across the current finance dataset (subject to any page filters).`,
  financePendingAmount: `Pending Amount includes payments that are not marked paid yet (awaiting confirmation).`,
  financePaidAmount: `Paid Amount includes payments with status PAID.`,
  financeOverdueAmount: `Overdue Amount includes payments past Payment Due Date that are not fully paid.`,
  dueDatePayment: `Payment Due Date is the contractual/latest due date used to determine overdue status.`,
  dpDate: `DP Date is the down payment date (if applicable).`,
  payoffDate: `Payoff Date is the final payoff date; blank payoff date is commonly used to indicate outstanding payment in dashboard logic.`,
  dpDeviationDays: `DP deviation (days) = DP Date - Due Date Payment (in days). Positive means DP happened after due date.`,
  payoffDeviationDays: `Payoff deviation (days) = Payoff Date - Due Date Payment (in days). Positive means payoff happened after due date.`,
} as const

export type FieldHelpKey = keyof typeof FIELD_HELP
